# This is a basic workflow that is manually triggered

name: Varios Jobs entrelazados

# Controls when the action will run
on:
# Allows you to run this workflow manually from the Actiones tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  extraer:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    #Check-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: ls .

  transformar:
    runs-on: ubuntu-latest
    needs: extraer
    steps:
      - run: echo Hola, mundo!

  cargar:
    runs-on: ubuntu-latest
    needs: transformar
    steps:
      - run: echo "Ya llegamos al final"
  
    
